# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

In [1]:
!pip install numpy


In [3]:
import numpy as np


In [9]:
data = np.array([1, 2, 3, 4, 5])

print(data)         
print(len(data))   
print(type(data))   
print(data.shape)   


[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


In [11]:
arr = np.array([[3, 2, 14],
                [9, 10, 12]])
indexes = np.where(arr == 9)
print(indexes)  


(array([1], dtype=int64), array([0], dtype=int64))


In [13]:
data = np.array([[9, 2, 5],
                 [4, 7, 1]])
sorted_flat = np.sort(data, axis=None)
print(sorted_flat)


[1 2 4 5 7 9]


In [15]:

data = np.array([['dog', 'apple', 'banana'],
                 ['cherry', 'elephant', 'bat']])
sorted_data = np.sort(data)
print(sorted_data)


[['apple' 'banana' 'dog']
 ['bat' 'cherry' 'elephant']]


In [17]:
arr = np.array([3, 2, 14, 9, 10, 12])
indexes = np.where(arr == 9)
print(indexes)


(array([3], dtype=int64),)


In [19]:
arr1 = np.array([9, 5, 8])
arr2 = np.array([55, 89, 76])
joined_array = np.concatenate((arr1, arr2))
print(joined_array)


[ 9  5  8 55 89 76]
